spring:
  application:
    name: catalog
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        accessKey: test
        secretKey: test
      endpoint: http://localhost:4566

app:
  queues:
    orderCreated: order-created-event

server:
  port: 8055

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
