spring:
  application:
    name: order

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/orders?authSource=admin
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        accessKey: test
        secretKey: test
      endpoint: http://localhost:4566
app:
  queues:
    orderCreated: order-created-event
server:
  port: 8056

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
