spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false